name: Check

on:
  push:
    branches:
      - master
      - main
    paths:
      - crosshair/**
      - setup.py
      - precommit.py
      - check_init_and_setup_coincide.py

  pull_request:
    paths:
      - crosshair/**
      - setup.py
      - precommit.py
      - check_init_and_setup_coincide.py

jobs:
  Execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          # There were breaking changes in 3.7.0 and we should test for it.
          # Unfortunately, GitHub does not support Python 3.7.0.
          3.7.1,
          3.8
        ]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .[dev]

      - name: Run checks
        env:
          PYTHONHASHSEED: 0
        run: |
          python3 precommit.py

  Send-to-codecov:
    name: Send to codecov
    needs: Execute
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Send to codecov
        run: |
          pip3 install --upgrade codecov
          codecov
